services:
  tasks:
    container_name: phen_machine
    build:
      context: tasks/
    environment:
      - REDIS_URL=${REDIS_URL}
      - FOLDER_DATA=${FOLDER_DATA}
    networks:
      phen-net:
        aliases:
          - phen-net-machine
    volumes:
      - "${PATH_TO_CACHE}:${FOLDER_DATA}"
    tty: true
    stdin_open: true

networks:
  phen-net:
    external: true
    name: phen-net
      
