services:
  tasks:
    build:
      context: tasks/
      dockerfile: Dockerfile.dev
    environment:
      - REDIS_URL=${REDIS_URL}
    networks:
      phen-net:
        aliases:
          - phen-net-machine
    volumes:
      - "./tasks:/app"
      - "${PATH_TO_CACHE}:/app/cache"
    tty: true
    stdin_open: true

networks:
  phen-net:
    external: true
    name: phen-net
      
