FROM python:3.12.4-bookworm

WORKDIR /app
RUN apt update
RUN apt install nano -y
COPY requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache-dir --upgrade -r requirements.txt

COPY . .

